title = 'OSR October'
baseURL = 'https://main--sweet-figolla-586142.netlify.app/'
languageCode = 'en-us'
theme = "ananke"
commentoEnable = true
disqusShortname = 'osr-role-playing'
backgroundImage = '/images/FadedFighter.png'

[params]
  body_classes = "baskervvile bg-near-white"
  post_content_classes = "baskervvile bg-near-white"
