title = 'OSR October'
baseURL = 'https://main--sweet-figolla-586142.netlify.app/'
languageCode = 'en-us'
theme = "ananke"
commentoEnable = true
disqusShortname = 'osr-role-playing'

[params]
  post_content_classes = "Baskerville, Garamond, Palatino, Times New Roman, Times bg-near-white"
