baseURL = 'https://main--sweet-figolla-586142.netlify.app/'
languageCode = 'en-us'
title = 'OSR October'
theme = "ananke"
commentoEnable = true
disqusShortname = 'osr-role-playing'
post_content_classes = "souvenir bg-near-white"
